# Generated by Django 3.0.11 on 2021-02-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('limit', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('answer_1', models.TextField()),
                ('logo_1', models.ImageField(blank=True, upload_to='upload')),
                ('answer_2', models.TextField()),
                ('logo_2', models.ImageField(blank=True, upload_to='upload')),
                ('answer_3', models.TextField()),
                ('logo_3', models.ImageField(blank=True, upload_to='upload')),
                ('answer_4', models.TextField()),
                ('logo_4', models.ImageField(blank=True, upload_to='upload')),
                ('answer_5', models.TextField()),
                ('logo_5', models.ImageField(blank=True, upload_to='upload')),
                ('correct_answer', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('ball', models.IntegerField(default=0)),
                ('count_question', models.IntegerField(default=0)),
                ('true_question', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_variant', models.IntegerField(default=0)),
                ('correct_variant', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestItem')),
                ('user_test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserTestItem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('ball', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
        ),
    ]
