# Generated by Django 3.0.11 on 2021-02-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestitem',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Test'),
        ),
        migrations.AddField(
            model_name='usertestitem',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AlterField(
            model_name='test',
            name='limit',
            field=models.IntegerField(default=40),
        ),
    ]
