# Generated by Django 3.0.11 on 2021-02-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='logo_1',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='logo_2',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='logo_3',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='logo_4',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='logo_5',
        ),
    ]
